[project]
name = "csie-fr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ruei326528", email = "ruei326528@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
csie-fr = "csie_fr:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
